// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-jBrFrvDPopEWDxTqlUiml5CSAjlzbY',
    appId: '1:231316845473:web:f2da7d6e576206750111e0',
    messagingSenderId: '231316845473',
    projectId: 'colorflood-1f8f0',
    authDomain: 'colorflood-1f8f0.firebaseapp.com',
    storageBucket: 'colorflood-1f8f0.firebasestorage.app',
    measurementId: 'G-WSZBSW8SWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL3OCg95216qyp1RHKGcAsm1YhZI8rA9Y',
    appId: '1:231316845473:android:5a14b0e7f0b488c30111e0',
    messagingSenderId: '231316845473',
    projectId: 'colorflood-1f8f0',
    storageBucket: 'colorflood-1f8f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Hi8YIECXhHUHjO0-RNl82V8-BE4WXBE',
    appId: '1:231316845473:ios:3449efe4283a30b30111e0',
    messagingSenderId: '231316845473',
    projectId: 'colorflood-1f8f0',
    storageBucket: 'colorflood-1f8f0.firebasestorage.app',
    iosBundleId: 'com.example.colorflood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Hi8YIECXhHUHjO0-RNl82V8-BE4WXBE',
    appId: '1:231316845473:ios:3449efe4283a30b30111e0',
    messagingSenderId: '231316845473',
    projectId: 'colorflood-1f8f0',
    storageBucket: 'colorflood-1f8f0.firebasestorage.app',
    iosBundleId: 'com.example.colorflood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn-jBrFrvDPopEWDxTqlUiml5CSAjlzbY',
    appId: '1:231316845473:web:2660dded29c7d0970111e0',
    messagingSenderId: '231316845473',
    projectId: 'colorflood-1f8f0',
    authDomain: 'colorflood-1f8f0.firebaseapp.com',
    storageBucket: 'colorflood-1f8f0.firebasestorage.app',
    measurementId: 'G-8N5P9EKHLT',
  );
}
